function ax0 = plotData(obj, ax0)

xFac = (ax0.Position(4)/0.85)^0.25;

ax0.Tag = 'plot';

mealTextPos = 450;
if isempty(obj.carbRatio) || xFac < 1
    bolusTextPos = mealTextPos - 20/xFac;
    basalTextPos = mealTextPos - 45/xFac;
else
    bolusTextPos = mealTextPos - 32;
    basalTextPos = mealTextPos - 55;
end
mealBolusSize = floor(12*xFac);
bolusDetailSize = floor(10*xFac);
mealBolusMarkerSize = floor(14*xFac);
blue = [0, 0.4470, 0.7410];
nightBlue = [0.2627, 0.2627, 0.4039];
red = [0.8500, 0.3250, 0.0980];
darkRed = [0.6350, 0.0780, 0.1840];
purple = [0.4940, 0.1840, 0.5560];
lightRed = [0.8824, 0.4627, 0.2118];
lightBlue = [0.1961, 0.3529, 0.5176];
magenta = [1.0, 0.0, 1.0];
timeToCombineMealsInMin = 0;

cla(ax0);
hold(ax0, 'on');

ylim(ax0, [0, mealTextPos+50])
multi80 = [ 1     2     4     5     8    10    16    20     40    80];
[~, idxCloseseMulti80] = min(abs(multi80 - 20/xFac^4.5));
yticks(ax0, 0:multi80(idxCloseseMulti80):400);

set(ax0, 'FontWeight', 'bold', 'LineWidth', 2.0, 'FontSize', 14);

ax0.XLabel.String = 'Time (HH:MM)';
ax0.YLabel.String = 'Sensor Glucose (mg/dl)';

title(ax0, sprintf('Data for participant %s: %s -> %s', obj.name, datestr(obj.startDate), datestr(obj.endDate)), 'FontSize', 16, 'Interpreter', 'none');

grid(ax0, 'on');
ax0.GridAlpha = 0.05;

% time
t = dateshift(obj.startDate, 'start', 'hour') + minutes(0:1:ceil(minutes(obj.duration)));

% target
plot(ax0, [t(1), t(end)], [180.0, 180.0], '-k');
plot(ax0, [t(1), t(end)], [70.0, 70.0], '-k');

% day & night
nightTime = [0 8]*60;
if nightTime(2) < nightTime(1)
    nightTime(2) = nightTime(2) + 1440;
end
for k = -1:ceil(days(obj.duration)) + 1
    patch(ax0, ...
        'XData', dateshift(obj.startDate, 'start', 'day') + minutes(24*60*(k - 1)+[nightTime(1), nightTime(2), nightTime(2), nightTime(1)]), ...
        'YData', [0, 0, 400, 400], ...
        'FaceColor', nightBlue, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.15 ...
        );
end

% bg
if obj.useBG && ~isempty(obj.bg)
    tg = obj.bg.time;
    plot(ax0, tg, obj.bg.value, ...
        'Color', 'k', ...
        'LineStyle', '-', ...
        'Marker', '.', ...
        'MarkerSize', round(20*xFac));
end

% cgm
if ~isempty(obj.cgm)
    tg = obj.cgm.time;
    plot(ax0, tg, obj.cgm.value, ...
        'Color', darkRed, ...
        'LineStyle', '-', ...
        'Marker', '.', ...
        'MarkerSize', round(20*xFac));
end

% smbg
if ~isempty(obj.smbg)
    ts = obj.smbg.time;
    if ~isempty(obj.cgm)
        plot(ax0, ts, obj.smbg.value, ...
            'Color', purple, ...
            'LineWidth', 2.0, ...
            'LineStyle', 'none', ...
            'Marker', '*', ...
            'MarkerSize', round(14*xFac));
    else
        plot(ax0, ts, obj.smbg.value, ...
            'Color', purple, ...
            'LineWidth', 2.0, ...
            'LineStyle', '-', ...
            'Marker', '*', ...
            'MarkerSize', round(14*xFac));
    end
end

% meal estimation
if ~isempty(obj.carbsCategory) && ~isempty(obj.carbsType)
    mealTypeName = {'B', 'L', 'D', 'S'};
    carbCategoryName = {'S', 'M', 'L'};
    tm = obj.carbsCategory.time;
    plotted_ = false(size(tm));
    for idx = find(obj.carbsCategory.value > 0)'
        if plotted_(idx) || tm(idx) > t(end) || tm(idx) < t(1)
            continue;
        end

        idx_close_ = find(abs(minutes(tm - tm(idx))) <= timeToCombineMealsInMin);

        MEAL = plot(ax0, tm(idx_close_(1)), mealTextPos+14.0, ...
            '-', ...
            'color', red, ...
            'Marker', '^', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', red, ...
            'MarkerEdgeColor', red);

        text(ax0, tm(idx), mealTextPos+28.0, sprintf('%s%s', mealTypeName{obj.carbsType.value(idx_close_)}, carbCategoryName{obj.carbsCategory.value(idx_close_)}), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', red, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        plotted_(idx_close_) = true;
    end
elseif ~isempty(obj.carbsCategory) && isempty(obj.carbsType)
    carbCategoryName = {'S', 'M', 'L'};
    tm = obj.carbsCategory.time;
    plotted_ = false(size(tm));
    for idx = find(obj.carbsCategory.value > 0)'
        if plotted_(idx) || tm(idx) > t(end) || tm(idx) < t(1)
            continue;
        end

        idx_close_ = find(abs(minutes(tm - tm(idx))) <= timeToCombineMealsInMin);

        MEAL = plot(ax0, tm(idx_close_(1)), mealTextPos+14.0, ...
            '-', ...
            'color', red, ...
            'Marker', '^', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', red, ...
            'MarkerEdgeColor', red);

        text(ax0, tm(idx), mealTextPos+28.0, sprintf('%s', carbCategoryName{obj.carbsCategory.value(idx_close_)}), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', red, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        plotted_(idx_close_) = true;
    end
end

% meals
if ~isempty(obj.carbs)
    tm = obj.carbs.time;
    plotted_ = false(size(tm));
    for idx = find(obj.carbs.value > 0)'
        if plotted_(idx) || tm(idx) > t(end) || tm(idx) < t(1)
            continue;
        end

        idx_close_ = find(abs(minutes(tm - tm(idx))) <= timeToCombineMealsInMin);

        MEAL = plot(ax0, tm(idx_close_(1)), mealTextPos+14/xFac^2.5, ...
            '-', ...
            'color', red, ...
            'Marker', '^', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', red, ...
            'MarkerEdgeColor', red);

        text(ax0, tm(idx), mealTextPos, sprintf('%2.0fg', sum(obj.carbs.value(idx_close_))), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', red, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        plotted_(idx_close_) = true;
    end
end

% actual meals
if ~isempty(obj.carbsActual)
    tma = obj.carbsActual.time;
    plotted_ = false(size(tma));
    for idx = find(obj.carbsActual.value > 0)'
        if plotted_(idx)
            continue;
        end

        idx_close_ = find(abs(minutes(tma - tma(idx))) <= timeToCombineMealsInMin);

        plot(ax0, tma(idx_close_(1)), mealTextPos+(14+25), ...
            '-', ...
            'color', purple, ...
            'Marker', '^', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', purple, ...
            'MarkerEdgeColor', purple);

        text(ax0, tma(idx), mealTextPos+25, sprintf('%2.0fg', sum(obj.carbsActual.value(idx_close_))), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', purple, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        plotted_(idx_close_) = true;
    end
end

% boluses
if ~isempty(obj.carbRatio)
    tcr = obj.carbRatio.time;
end
if ~isempty(obj.bolus)
    tbo = obj.bolus.time;
    plotted_ = false(size(tbo));
    for idx = find(obj.bolus.value > 0)'
        if plotted_(idx) || tbo(idx) > t(end) || tbo(idx) < t(1)
            continue;
        end

        idx_close_ = find(abs(minutes(tbo - tbo(idx))) <= timeToCombineMealsInMin);

        BOLUS = plot(ax0, tbo(idx_close_(1)), bolusTextPos, ...
            '-', ...
            'color', blue, ...
            'Marker', 'v', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', blue, ...
            'MarkerEdgeColor', blue);

        if length(tbo) > 300
            continue;
        end

        totBolus = sum(obj.bolus.value(idx_close_));
        text(ax0, tbo(idx), bolusTextPos+5/xFac^2.5, sprintf('%3.1fu', totBolus), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', blue, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        if ~isempty(obj.carbRatio) && ~isempty(obj.carbs) && xFac >= 1
            totCarb = sum(obj.carbs.value(find(abs(minutes(tm - tbo(idx))) <= timeToCombineMealsInMin)));
            if ~isempty(totCarb) && totCarb > 0
                if sum(tcr <= tbo(idx)) == 0
                    cr = obj.carbRatio.value(end);
                else
                    cr = obj.carbRatio.value(sum(tcr <= tbo(idx)));
                end
                mealBolus = totCarb / cr;
                text(ax0, tbo(idx), bolusTextPos+24, sprintf('\\div%3.1f', cr), ...
                    'VerticalAlignment', 'bottom', ...
                    'HorizontalAlignment', 'center', ...
                    'Color', lightRed, ...
                    'FontSize', bolusDetailSize, ...
                    'FontWeight', 'bold');

                if round(totBolus, 1) ~= round(mealBolus, 1)
                    text(ax0, tbo(idx), bolusTextPos+17, sprintf('%+3.1f', round(totBolus, 1) - round(mealBolus, 1)), ...
                        'VerticalAlignment', 'bottom', ...
                        'HorizontalAlignment', 'center', ...
                        'Color', lightBlue, ...
                        'FontSize', bolusDetailSize, ...
                        'FontWeight', 'bold');
                end
                text(ax0, tbo(idx), bolusTextPos+15, '\_\_\_\_\_', ...
                    'VerticalAlignment', 'bottom', ...
                    'HorizontalAlignment', 'center', ...
                    'Color', lightBlue, ...
                    'FontSize', 10, ...
                    'FontWeight', 'bold');
            end
        end

        plotted_(idx_close_) = true;
    end
end

% basalInj
if ~isempty(obj.basalInj)
    tbainj = obj.basalInj.time;
    plotted_ = false(size(tbainj));
    for idx = 1:length(tbainj)
        if plotted_(idx)
            continue;
        end

        idx_close_ = find(abs(minutes(tbainj - tbainj(idx))) <= timeToCombineMealsInMin);

        BASAL_INJ = plot(ax0, tbainj(idx_close_(1)), basalTextPos-5/xFac^2.5, ...
            '-', ...
            'color', blue, ...
            'Marker', 'o', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', blue, ...
            'MarkerEdgeColor', blue);

        text(ax0, tbainj(idx), basalTextPos, sprintf('%3.1fu', sum(obj.basalInj.value(idx_close_))), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', blue, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        plotted_(idx_close_) = true;
    end
end

% treats
if ~isempty(obj.treat)
    tt = obj.treat.time;
    plotted_ = false(size(tt));
    for idx = 1:length(tt)
        if plotted_(idx)
            continue;
        end

        idx_close_ = find(abs(minutes(tt - tt(idx))) <= timeToCombineMealsInMin);

        TREAT = plot(ax0, tt(idx_close_(1)), basalTextPos+14.0/xFac^2.5, ...
            '-', ...
            'color', purple, ...
            'Marker', '^', ...
            'MarkerSize', mealBolusMarkerSize, ...
            'MarkerFaceColor', purple, ...
            'MarkerEdgeColor', purple);

        text(ax0, tt(idx), basalTextPos, sprintf('%2.0fg', sum(obj.treat.value(idx_close_))), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'center', ...
            'Color', purple, ...
            'FontSize', mealBolusSize, ...
            'FontWeight', 'bold');

        plotted_(idx_close_) = true;
    end
end

xlim(ax0, [t(1) - minutes(30), t(end) + minutes(30)]);

% basal rate
if ~isempty(obj.basalRate)
    yyaxis(ax0, 'right');
    cla(ax0);

    tbarate = obj.basalRate.time;
    tbarate_end = tbarate(end) + minutes(30);
    stairs(ax0, [tbarate; tbarate_end], [obj.basalRate.value; obj.basalRate.value(end)], ...
        'Color', blue, ...
        'LineStyle', '-', ...
        'LineWidth', 2.0);

    ax0.YAxis(2).Color = [0, 0, 0];
    ax0.YLabel.String = 'Insulin Rate (U/h)';
    ax0.YLim = [0, round((mealTextPos+50)/20)];
    ax0.YTick = (0:1:round(400/20));

    yyaxis(ax0, 'left');
end
